---
- include_role: {name: corpusops.roles/services_virt_docker}
  tags: [docker_setup]

- set_fact:
    matrix_host_dirs: |
        {% set directories = [] %}
        {% for matrix_volume in (matrix_coturn_volumes+
                                 matrix_volumes+
                                 matrix_db_volumes) %}
        {% set d = matrix_volume.split(':')[0] %}
        {% set _ = directories.append(d) %}
        {% endfor %}
        {{ directories | to_json }}

- include_tasks: configs.yml
  tags: [configs]

- include_role: {name: corpusops.roles/docker_compose_service}
  vars:
    _docker_compose_service:
      state: restarted
      project: "{{matrix_compose_project}}"
      working_directory: "{{matrix_volumes_hostdir}}"
  tags: [dockercomposeservice]
