---
- template:
    src: pillar.sls
    dest: /srv/makina-states/pillar/private.pillar.d/matrix.sls
    mode: "0600"
  tags: [haproxy]
- shell: |
    salt-call -lall --retcode-passthrough \
      state.sls makina-states.services.proxy.haproxy
  tags: [haproxy]
- file:
    state: absent
    dest: /etc/ms_iptables.d/makneb.json
  tags: [ms_iptables]
  when: not matrix_makneb_clients
- template:
    dest: /etc/ms_iptables.d/makneb.json
    src: msiptables.json
    mode: "0644"
  tags: [ms_iptables]
  when: matrix_makneb_clients
- shell: |
    salt-call -lall --retcode-passthrough \
      state.sls makina-states.services.firewall.ms_iptables
  tags: [ms_iptables]
