---
matrix_image: "corpusops/docker-matrix:v0.33.8"
matrix_riot_image: "corpusops/riot:0.17.5"
matrix_dimension_image: "corpusops/matrix-dimension:latest"
matrix_mxisd_image: kamax/mxisd
matrix_pg_image: corpusops/postgresql:9.6.5
matrix_network: 172.18.0
matrix_int_ip: "{{matrix_network}}.2"
matrix_coturn_int_ip: "{{matrix_network}}.9"
matrix_domain: matrix.foo.net
matrix_coturn_domain: coturn.foo.net
matrix_mxisd_domain: matrixid.foo.net
matrix_riot_domain: riot.foo.net
matrix_dimension_domain: dimension.foo.net
matrix_makneb_domain: makneb.foo.net
matrix_db_password: xxx
matrix_crt: "{{corpusops_ssl_certs['*.foo.net'][0]}}"
matrix_key: "{{corpusops_ssl_certs['*.foo.net'][1]}}"
matrix_ldap_dn: "cn=matrixreader,ou=People,dc=foo,dc=org"
matrix_ldap_pw: "xxx"
matrix_dh: |
  2048-bit DH parameters taken from rfc3526
  -----BEGIN DH PARAMETERS-----
  xxx
  -----END DH PARAMETERS-----
matrix_signing_key: "ed25519 xxx"
matrix_macaroon_secret_key: "xxx"
matrix_ldap_host: "ldap.foo.net"
matrix_ldap_bdn: "dc=foo,dc=org"
matrix_ldap_mailattr: "shortMail"
#
matrix_tid_servers: [matrix.org, vector.im, riot.im]
matrix_goneb_image: corpusops/go-neb
matrix_backup_image: corpusops/dbsmartbackup:3
matrix_xforwarded: true
matrix_compose_project: "compose-matrix"
matrix_coturn_image: corpusops/docker-coturn:4.5.0.7
matrix_ip: 127.0.0.1
matrix_http_port: 19000
matrix_riot_port: 19002
matrix_mxisd_port: 19003
matrix_https_port: 19001
matrix_makneb_port: 19004
matrix_dimension_port: 19005
matrix_public_http_port: 80
matrix_public_https_port: 443
matrix_pgsql_conf:
  cops_postgresql__roles:
    - name: dbuser
      password: "{{matrix_db_password}}"
  cops_postgresql__databases:
    - db: db
      owner: dbuser
matrix_hosts: ["{{matrix_domain}}"]
matrix_dimension_hosts: ["{{matrix_dimension_domain}}"]
matrix_mxisd_hosts: ["{{matrix_mxisd_domain}}"]
matrix_riot_hosts: ["{{matrix_riot_domain}}"]
matrix_makneb_hosts: ["{{matrix_riot_domain}}"]
matrix_volumes_hostdir: /srv/data/matrix
matrix_dimension_data: "{{matrix_volumes_hostdir}}/dimension"
matrix_dimension_volumes:
  - "{{matrix_dimension_data}}:/data"
matrix_mxisd_volumes:
  - "{{matrix_volumes_hostdir}}/matrix-id:/var/mxisd"
  - "{{matrix_volumes_hostdir}}/matrix-id-conf/mxisd_start.sh:/mxisd_start.sh"
  - "{{matrix_volumes_hostdir}}/matrix-id-conf:/etc/mxisd"
matrix_volumes:
  - "{{matrix_volumes_hostdir}}/matrix-data:/data"
matrix_coturn_volumes:
  - "{{matrix_volumes_hostdir}}/coturn-data:/data"
matrix_goneb_volumes:
  - "{{matrix_volumes_hostdir}}/goneb:/data"
matrix_db_volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - "{{matrix_volumes_hostdir}}/db-reconfigure.yml:/setup/reconfigure.yml:ro"
  - "{{matrix_volumes_hostdir}}/pgsql:/var/lib/postgresql"
matrix_backup_volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - "{{matrix_volumes_hostdir}}/backup/data:/srv/backups"
  - "{{matrix_volumes_hostdir}}/backup/setup/reconfigure.yml:/setup/reconfigure.yml:ro"
matrix_url_preview_enabled: True
matrix_enable_metrics: False
matrix_report_stats: False
matrix_enable_group_creation: False
matrix_mxisd:
  server.name: "{{matrix_mxisd_hosts[0]}}"
  matrix.domain: "{{matrix_hosts[0]}}"
  # maintained by image
  key.path: '/var/mxisd/sign.key'
  storage.provider.sqlite.database: '/var/mxisd/mxisd.db'
  ldap.enabled: true
  ldap.connection.host: "{{matrix_ldap_host}}"
  ldap.connection.bindDn: "{{matrix_ldap_dn}}"
  ldap.connection.bindPassword: "{{matrix_ldap_pw}}"
  ldap.connection.baseDn: "{{matrix_ldap_bdn}}"
  ldap.connection.tls: false
  ldap.connection.port: 389
  ldap.filter: "(objectClass=person)"
  ldap.attribute.uid.type: 'uid'
  ldap.attribute.uid.value: 'uid'
  ldap.attribute.name: 'uid'
  ldap.attribute.threepid.email: ["{{matrix_ldap_mailattr}}", "mail"]
matrix_url_preview_ip_range_whitelist: []
matrix_coturn_secret: "supercret64chars"
matrix_coturn_realm: "{{ansible_domain}}"
matrix_coturn_crt: "{{matrix_crt}}"
matrix_coturn_key: "{{matrix_key}}"
matrix_makneb_clients: [127.0.0.1]
matrix_url_preview_ip_range_blacklist:
- '127.0.0.0/8'
- '10.0.0.0/8'
- '172.16.0.0/12'
- '192.168.0.0/16'
- '100.64.0.0/10'
- '169.254.0.0/16'
matrix_externalip: ""
matrix_coturn: true
matrix_coturn_port: 3478
matrix_coturn_altport: 3479
matrix_coturn_tlsport: 5349
matrix_coturn_alttlsport: 5350
matrix_coturn_minport: 49152
matrix_coturn_maxport: 65535
matrix_coturn_dh_file: "/data/{{matrix_domain}}.tls.dh"
matrix_coturn_notcprelay: true
matrix_coturn_quota: 4000
matrix_coturn_userquota: 40
matrix_coturn_deniedip: []
#- 10.0.0.0-10.255.255.255
#- 192.168.0.0-192.168.255.255
#- 172.16.0.0-172.31.255.255
matrix_coturn_user_lifetime: 86400000
matrix_turn_uris:
- "turn:{{matrix_domain}}:{{matrix_coturn_port}}?transport=udp"
- "turn:{{matrix_domain}}:{{matrix_coturn_port}}?transport=tcp"
matrix_coturn_notls1: true
matrix_db_ip: "{{matrix_network}}.8"
matrix_email:
  enable_notifs: true
  smtp_host: 'mail.foo.net'
  smtp_port: 587
  notif_from: 'foo matrix <sysadmin@foo.com>'
  notif_for_new_users: true
  smtp_auth: true
  smtp_user: 'bar@foo.com'
  smtp_pass: 'xxx'
  riot_base_url: 'https://matrix.foo.com'
  require_transport_security: true
  # copy the content of
  # -> https://github.com/matrix-org/synapse/tree/master/res
  # to /data volume
  template_dir: "/data/res/templates"
  notif_template_html: "notif_mail.html"
  notif_template_text: "notif_mail.txt"
matrix_dimension_hs: "{{matrix_domain}}"
matrix_dimension_client_server_url: "https://{{matrix_domain}}"
matrix_dimension_access_token: "xxxxxx"
matrix_dimension_federation_url: null
matrix_dimension_media_url: null
matrix_dimension_admins: []
matrix_dimension_widget_blacklist:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
- 127.0.0.0/8

matrix_log_level: "ERROR"
matrix_log_level_storage: "{{matrix_log_level}}"
matrix_log_level_synapse: "WARN"
matrix_log_level_root: "{{matrix_log_level}}"
matrix_app_service_config_files: []
matrix_integrations_url:               ""
matrix_integrations_api_url:           ""
matrix_integrations_widgets_urls:      ""
matrix_integrations_jitsi_widgets_url: ""
# matrix_integrations_url:                "https://{{matrix_dimension_domain}}/riot"
# matrix_integrations_api_url:            "https://{{matrix_dimension_domain}}/api/v1/scalar"
# matrix_integrations_widgets_urls:      ["https://{{matrix_dimension_domain}}/widgets"]
# matrix_integrations_jitsi_widgets_url:  "https://{{matrix_dimension_domain}}/widgets/jitsi"
