---
matrix_image: "corpusops/docker-matrix:v1.51.0"
matrix_simple_image: "{{matrix_image}}"
matrix_riot_image: "corpusops/riot:1.10.0"
matrix_simple_riot_image: "{{matrix_riot_image}}"
matrix_simple_dimension_image: "corpusops/matrix-dimension:2"
matrix_dimension_image: "corpusops/matrix-dimension"
matrix_mxisd_image: kamax/mxisd
matrix_ma1sd_image: ma1uta/ma1sd
matrix_pg_image: corpusops/postgresql:9.6.5
matrix_simple_pg_image: corpusops/postgres:13
matrix_network: 172.18.0
matrix_int_ip: "{{matrix_network}}.2"
matrix_domain: matrix.foo.net
matrix_mxisd_domain: matrixid.foo.net
matrix_riot_domain: riot.foo.net
matrix_dimension_domain: dimension.foo.net
matrix_goneb_domain: goneb.foo.net
matrix_db_password: xxx
matrix_crt: "{{corpusops_ssl_certs['*.foo.net'][0]}}"
matrix_key: "{{corpusops_ssl_certs['*.foo.net'][1]}}"
matrix_ldap_dn: "cn=matrixreader,ou=People,dc=foo,dc=org"
matrix_ldap_pw: "xxx"
matrix_dh: |
  2048-bit DH parameters taken from rfc3526
  -----BEGIN DH PARAMETERS-----
  xxx
  -----END DH PARAMETERS-----
matrix_signing_key: "ed25519 xxx"
matrix_macaroon_secret_key: "xxx"
matrix_ldap_host: "ldap.foo.net"
matrix_ldap_bdn: "dc=foo,dc=org"
matrix_ldap_mailattr: "shortMail"
#
matrix_tid_servers: [matrix.org, vector.im, riot.im]
matrix_simple_goneb_image: corpusops/go-neb:1
matrix_goneb_image: corpusops/go-neb
matrix_backup_image: corpusops/dbsmartbackup:postgres-{{matrix_pg_new}}
matrix_xforwarded: true
matrix_compose_project: "{{matrix_volumes_hostdir|copsf_basename}}"
matrix_ip: 127.0.0.1
matrix_http_port: 19000
matrix_https_port: 19001
matrix_riot_port: 19002
matrix_mxisd_port: 19003
matrix_tls_port: 8448
matrix_goneb_port: 19004
matrix_dimension_port: 19005
matrix_public_http_port: 80
matrix_public_https_port: 443
matrix_pgsql_conf:
  cops_postgresql__roles:
    - name: dbuser
      password: "{{matrix_db_password}}"
  cops_postgresql__databases:
    - db: db
      owner: dbuser
matrix_dbs_compression: nocomp
matrix_hosts: ["{{matrix_domain}}"]
matrix_goneb_hosts: ["{{matrix_goneb_domain}}"]
matrix_dimension_hosts: ["{{matrix_dimension_domain}}"]
matrix_mxisd_hosts: ["{{matrix_mxisd_domain}}"]
matrix_riot_hosts: ["{{matrix_riot_domain}}"]
matrix_volumes_hostdir: /srv/docker/matrix
matrix_dimension_data: "{{matrix_volumes_hostdir}}/dimension"
matrix_dimension_volumes:
  - "{{matrix_dimension_data}}:/data"
matrix_ma1sd_volumes:
  - "{{matrix_volumes_hostdir}}/matrix-id/ma1sd:/var/ma1sd"
  - "{{matrix_volumes_hostdir}}/matrix-id-conf:/etc/ma1sd"
matrix_mxisd_volumes:
  - "{{matrix_volumes_hostdir}}/matrix-id:/var/mxisd"
  - "{{matrix_volumes_hostdir}}/matrix-id-conf:/etc/mxisd"
#  - "{{matrix_volumes_hostdir}}/matrix-id-conf/mxisd_start.sh:/mxisd_start.sh"
matrix_volumes:
  - "{{matrix_volumes_hostdir}}/matrix-data:/data"
matrix_goneb_volumes:
  - "{{matrix_volumes_hostdir}}/goneb:/data"
matrix_simple_db_volumes:
  - "{{matrix_volumes_hostdir}}/pgsql:/var/lib/postgresql/data"
matrix_db_volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - "{{matrix_volumes_hostdir}}/db-reconfigure.yml:/setup/reconfigure.yml:ro"
  - "{{matrix_volumes_hostdir}}/pgsql:/var/lib/postgresql"
matrix_backup_volumes:
  - "{{matrix_volumes_hostdir}}/backup/data:/var/db_smart_backup"
matrix_url_preview_enabled: True
matrix_enable_metrics: False
matrix_report_stats: False
matrix_enable_group_creation: False
matrix_mxisd:
  server:
    name: "{{matrix_mxisd_hosts[0]}}"
  matrix:
    domain: "{{matrix_hosts[0]}}"
  # maintained by image
  key:
    path: '/var/mxisd/sign.key'
  storage:
    provider:
      sqlite:
        database: '/var/mxisd/mxisd.db'
  ldap:
    enabled: true
    connection:
      host: "{{matrix_ldap_host}}"
      bindDn: "{{matrix_ldap_dn}}"
      bindPassword: "{{matrix_ldap_pw}}"
      baseDn: "{{matrix_ldap_bdn}}"
      tls: false
      port: 389
    filter: "(objectClass=person)"
    attribute:
      uid.type: 'uid'
      uid.value: 'uid'
      name: 'uid'
      threepid.email: ["{{matrix_ldap_mailattr}}", "mail"]
matrix_ma1sd:
  key:
    path: '/var/ma1sd/sign.key'
  matrix:
    domain: "{{matrix_hosts[0]}}"
  server:
    name: "{{matrix_mxisd_hosts[0]}}"
  storage:
    provider:
      sqlite:
        database: '/var/ma1sd/ma1sd.db'
  ldap:
    attribute:
      name: uid
      threepid:
        email: ["{{matrix_ldap_mailattr}}", "mail"]
      uid: {type: uid, value: uid}
    connection:
      baseDn: "{{matrix_ldap_bdn}}"
      bindDn: "{{matrix_ldap_dn}}"
      bindPassword: "{{matrix_ldap_pw}}"
      host: "{{matrix_ldap_host}}"
      port: 389
      tls: false
    enabled: true
    filter: (objectClass=person)
matrix_externalip: ""
matrix_url_preview_ip_range_whitelist: []
matrix_db_ip: "{{matrix_network}}.8"
matrix_email:
  enable_notifs: true
  smtp_host: 'mail.foo.net'
  smtp_port: 587
  notif_from: 'foo matrix <sysadmin@foo.com>'
  notif_for_new_users: true
  smtp_auth: true
  smtp_user: 'bar@foo.com'
  smtp_pass: 'xxx'
  riot_base_url: 'https://matrix.foo.com'
  require_transport_security: true
  # copy the content of
  # -> https://github.com/matrix-org/synapse/tree/master/res
  # to /data volume
  notif_template_html: "notif_mail.html"
  notif_template_text: "notif_mail.txt"
matrix_dimension_hs: "{{matrix_domain}}"
matrix_dimension_client_server_url: "https://{{matrix_domain}}:8448"
matrix_dimension_access_token: "xxxxxx"
matrix_dimension_federation_url: null
matrix_dimension_media_url: null
matrix_dimension_admins: []
matrix_dimension_widget_blacklist:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
- 127.0.0.0/8

matrix_log_level: "ERROR"
matrix_log_level_storage: "{{matrix_log_level}}"
matrix_log_level_synapse: "WARN"
matrix_log_level_root: "{{matrix_log_level}}"
matrix_app_service_config_files: []
matrix_integrations_url:               ""
matrix_integrations_api_url:           ""
matrix_integrations_widgets_urls:      ""
matrix_integrations_jitsi_widgets_url: ""
# matrix_integrations_url:                "https://{{matrix_dimension_domain}}/element"
# matrix_integrations_api_url:            "https://{{matrix_dimension_domain}}/api/v1/scalar"
# matrix_integrations_widgets_urls:      ["https://{{matrix_dimension_domain}}/widgets"]
# matrix_integrations_jitsi_widgets_url:  "https://{{matrix_dimension_domain}}/widgets/jitsi"
matrix_orig_host: null
matrix_orig_path: /srv/data/matrix
matrix_dest_buf: /srv/nobackup/transfert
matrix_dest_buf_pgsql: "{{matrix_dest_buf}}/pgsql/9.6/main"
matrix_db_name: db
matrix_db_port: 5432
matrix_db_user: dbuser
matrix_riot_theme:  dark
matrix_docker_dot_env: |-
  COMPOSE_PROJECT_NAME={{matrix_compose_project}}
  POSTGRES_USER={{matrix_db_user}}
  POSTGRES_PASSWORD={{matrix_db_password}}
  POSTGRES_HOST={{matrix_db_ip}}
  POSTGRES_PORT={{matrix_db_port}}
  POSTGRES_DB={{matrix_db_name}}
  PGPASSWD={{matrix_db_password}}
  PGPASSWORD={{matrix_db_password}}
  DEFAULT_THEME={{matrix_riot_theme}}
  DEFAULT_HS_URL=https://{{matrix_domain}}
  DEFAULT_IS_URL=https://{{matrix_mxisd_hosts[0]}}
  INTEGRATIONS_UI_URL={{matrix_integrations_url}}
  INTEGRATIONS_REST_URL={{matrix_integrations_api_url}}
  INTEGRATIONS_WIDGETS_URL={{matrix_integrations_widgets_urls|to_json}}
  INTEGRATIONS_WIDGETSJITSI_URL={{matrix_integrations_jitsi_widgets_url}}
  DOCKERIZE_VERSION=v0.6.0
  MATRIX_DOMAIN={{matrix_domain}}
  PGLOCALE={{matrix_pg_locale}}
  PGLOCALES={{matrix_pg_locales}}
  JITSI={{matrix_jitsi}}
  GONEB_CLIENTS={{' '.join(matrix_goneb_clients)}}
  {% set a = matrix_mxisd_hosts + matrix_default_is %}
  ID_SERVERS={{(a|to_json)}}
  MATRIX_DOMAIN={{matrix_domain}}
  MXISD_DOMAIN={{matrix_mxisd_domain}}
  GONEB_DOMAIN={{matrix_goneb_domain}}
  RIOT_DOMAIN={{matrix_riot_domain}}
  DIMENSION_DOMAIN={{matrix_dimension_domain}}
  NGINX_REAL_IP_FROM={{matrix_real_ip_from}}
matrix_default_is: [matrix.org, vector.im]
matrix_real_ip_from: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 {{matrix_network}}.0/12"
matrix_jitsi: jitsi.riot.im
custom_template_directory: matrix_keep_dumps: "1"
matrix_restart_policy: unless-stopped
matrix_listen_if: 0.0.0.0
matrix_listen_int_if: 127.0.0.1
matrix_dcompose: docker-compose -p {{matrix_compose_project}} -f docker-compose.yml
matrix_pgup_img: tianon/postgres-upgrade:{{matrix_pg_old}}-to-{{matrix_pg_new}}
matrix_pg_new: 13
matrix_pg_locales: C.UTF-8 fr_FR.UTF-8 en_US.UTF-8
matrix_pg_locale: "{{matrix_pg_locales.split()[0]}}"
matrix_pg_old: 9.6
matrix_pgold_image: corpusops/postgres:{{matrix_pg_old}}
matrix_upgrade_pgsl_on_migrate: true
matrix_traefik_extra: ""
matrix_goneb_clients: [127.0.0.1]
matrix_url_preview_ip_range_blacklist:
- '127.0.0.0/8'
- '10.0.0.0/8'
- '172.16.0.0/12'
- '192.168.0.0/16'
- '100.64.0.0/10'
- '169.254.0.0/16'
#
# coturn is now disabled
matrix_coturn: false
matrix_coturn_secret: "supercret64chars"
matrix_coturn_realm: "{{ansible_domain}}"
matrix_coturn_crt: "{{matrix_crt}}"
matrix_coturn_key: "{{matrix_key}}"
matrix_coturn_port: 3478
matrix_coturn_altport: 3479
matrix_coturn_tlsport: 5349
matrix_coturn_alttlsport: 5350
matrix_coturn_minport: 49152
matrix_coturn_maxport: 50000
matrix_coturn_dh_file: "/data/{{matrix_domain}}.tls.dh"
matrix_coturn_notcprelay: true
matrix_coturn_quota: 4000
matrix_coturn_userquota: 40
matrix_registration_key: "FEBjXXCPYRBbSh5KXP3BoCDkd6hKYY4KjXECNtT5abj4Xhmq78pYztsTmEG7nQFByC35RxgYjNhkYMKpG"
matrix_coturn_deniedip:
- 10.0.0.0-10.255.255.255
- 192.168.0.0-192.168.255.255
- 172.16.0.0-172.31.255.255
matrix_coturn_user_lifetime: 86400000
matrix_turn_uris:
- "turn:{{matrix_domain}}:{{matrix_coturn_port}}?transport=udp"
- "turn:{{matrix_domain}}:{{matrix_coturn_port}}?transport=tcp"
matrix_coturn_notls1: true
matrix_coturn_image: corpusops/docker-coturn:4.5.0.7
matrix_simple_coturn_image: corpusops/docker-coturn:4.5.1.3
matrix_cleanup_old_db: true
matrix_coturn_domain: coturn.foo.net
matrix_coturn_int_ip: "{{matrix_network}}.9"
matrix_coturn_volumes:
- "{{matrix_volumes_hostdir}}/coturn-data:/data"
matrix_started_state: started
matrix_stdout: "null"
matrix_stderr: "null"
