---
cops_dbsmartbackup_confs:
  matrix:
    conf_path: /srv/backups/matrix.conf
    keep_lasts: 1
    type: postgresql
    keep_days: 2
    keep_logs: 7
    _periodicity: "0 3 * * *"
    free_form: |
      export HOST="{{matrix_db_ip}}"
      export PORT="5432"
      export DBNAMES="db"
      export PASSWORD="{{matrix_db_password}}"
      export DBUSER="dbuser"
      export PGUSER="$DBUSER"
      export RUNAS=""
      export PGPASSWORD="$PASSWORD"
