---
# {{ansible_managed}}
version: '3.7'
x-blocks:
  env: &env
    env_file: [.env]
  restart: &restart
    restart: "{{matrix_restart_policy}}"
networks:
  app_net:
    driver: bridge
    ipam: {driver: default, config: [{subnet: "{{matrix_network}}.0/24"}]}
services:
  db: &db
    <<: [ *env, *restart ]
    networks: {app_net: {ipv4_address: "{{matrix_network}}.8"}}
    image: "{{matrix_simple_pg_image}}"
    security_opt: ["seccomp=unconfined"]
    volumes: {{ matrix_simple_db_volumes|to_json }}
    # matrix makes mandatory of C locale
    environment: [LANG=C.UTF-8, LC_ALL=C.UTF-8]
  web: &web
    <<: [ *env, *restart ]
    networks: {app_net: {ipv4_address: "{{matrix_int_ip}}"}}
    extra_hosts:
    - "{{matrix_domain}}:{{matrix_int_ip}}"
    image: "{{matrix_simple_image}}"
    hostname: "{{matrix_domain}}"
    ports:
    {% if matrix_http_port %}- "{{matrix_listen_int_if}}:{{matrix_http_port}}:8008"{% endif %}
    {% if matrix_https_port %}- "{{matrix_listen_int_if}}:{{matrix_https_port}}:8448"{% endif %}
    {% if matrix_tls_port %}- "{{matrix_listen_if}}:{{matrix_tls_port}}:8448"{% endif%}
    entrypoint:
      - bash
      - "-exc"
      - >-
        cp -frnv /usr/local/lib/python*/*-packages/synapse/res/templates/* /data/res/templates/;
        if [ -f /ready ] ;then rm -f /ready;fi;
        ( set +ex;while true;do echo 'select 1' |psql -vON_ERROR_STOP=1
        'postgres://dbuser:{{matrix_db_password}}@db:5432/db'
        && touch /ready && break;
        sleep 1; echo retry db;done; )&
        dockerize -wait "file:///ready" -timeout 300s;
        exec ./start.py
    volumes: {{matrix_volumes|to_json}}
  riot:
    <<: [ *env, *restart ]
    image: "{{matrix_simple_riot_image}}"
    hostname: "{{matrix_riot_hosts[0]}}"
    networks: {app_net: {ipv4_address: "{{matrix_network}}.3"}}
    environment:
    - "DOMAINS={{matrix_riot_domain}}"
    # logging is on lb
    - "NGINX_ACCESSLOG=${RIOT_NGINX_ACCESSLOG:-off}"
    ports:
    - "{{matrix_listen_int_if}}:{{matrix_riot_port}}:8080"
  ma1sd:
    <<: [ *env, *restart ]
    image: "{{matrix_ma1sd_image}}"
    networks: {app_net: {ipv4_address: "{{matrix_network}}.4"}}
    environment:
    - "MATRIX_DOMAIN={{matrix_hosts[0]}}"
    hostname: "{{matrix_mxisd_hosts[0]}}"
    #entrypoint:
    #  - sh
    #  - -c
    #  - >
    #    apk update && apk add bash
    #    && /mxisd_start.sh
    volumes: {{matrix_ma1sd_volumes|to_json}}
    ports:
    - "{{matrix_listen_int_if}}:{{matrix_mxisd_port}}:8090"
  goneb:
    <<: [ *env, *restart ]
    image: "{{matrix_simple_goneb_image}}"
    networks: {app_net: {ipv4_address: "{{matrix_network}}.5"}}
    environment:
    - "BASE_URL=http://localhost:4050"
    extra_hosts:
    - "{{matrix_domain}}:{{matrix_int_ip}}"
    ports:
    - "{{matrix_listen_if}}:{{matrix_goneb_port}}:4050"
    volumes: {{matrix_goneb_volumes|to_json}}
  backup:
    <<: [ *env, *restart ]
    image: "{{matrix_backup_image}}"
    networks: {app_net: {ipv4_address: "{{matrix_network}}.10"}}
    volumes: {{matrix_backup_volumes|to_json}}
    environment:
    - "DBNAMES={{matrix_db_name}}"
    - "COMP={{matrix_dbs_compression}}"
    - "KEEP_LASTS={{matrix_keep_dumps}}"
    - "KEEP_DAYS={{matrix_keep_dumps}}"
    - "KEEP_MONTHES=0"
    - "KEEP_WEEKS=0"
  dimension:
    <<: [ *env, *restart ]
    image: "{{matrix_simple_dimension_image}}"
    networks: {app_net: {ipv4_address: "{{matrix_network}}.11"}}
    environment: []
    ports:
    - "{{matrix_listen_if}}:{{matrix_dimension_port}}:8184"
    volumes: {{matrix_dimension_volumes|to_json}}
  lb:
    <<: [ *env, *restart ]
    image: corpusops/nginx:1.19-alpine
    networks: {app_net: {ipv4_address: "{{matrix_network}}.12"}}
    entrypoint:
    - /bin/sh
    - "-exc"
    - |-
      frep /nginx/vhost.conf.frep:/etc/nginx/conf.d/default.conf --overwrite
      exec supervisord.sh
    environment: ["SUPERVISORD_CONFIGS=cron rsyslog nginx"]
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./nginx/logs:/logs
    - ./nginx:/certs
    - ./nginx:/nginx
    ports:
    - "{{matrix_listen_if}}:{{matrix_public_http_port}}:80"
    - "{{matrix_listen_if}}:{{matrix_public_https_port}}:80"
    depends_on: [riot, dimension, web, goneb, ma1sd]
# vim: set ft=sls :
